### ISSUE TITLE
Clarification for toleration

### ISSUE THREAD

**Issue by ebioman** [seqeralabs/nf-k8s-best-practices#1]
Hi
Thanks a lot for these resources, very much appreciated!
I am struggling with some kubernetes specific options, or more how to translate the k8 doc provided examples from yaml into nextflow.
E.g. I am trying to add toleration to the pod specification in a process and would need:
```
nodeSelector:
    type: fatnode
tolerations:
    - key: autoSchedule
      operator: "Exists"
      effect: "NoSchedule"
```
Now for the node-selector this is more easy, but toleration is something which I cant wrap my head around:

```
pod toleration: "key: autoSchedule", operator: "Exists", effect: "NoSchedule"
```
This obviously doesnt work, but so failed all my other attempt :)
Any hints?
